blueprint:
  name: Automatizacion Luces por Presencia
  description: Automatizaciones de las luces por presencia
  domain: automation
  source_url: https://github.com/dmarofer/BLUEPRINTSHA/blob/main/luces_pir_dmarofer.yaml
  input:
    grupo_luces:
      name: Grupo de luces de la estancia
      description: Las luces o grupos a controlar (para apagar)
      selector:
        target:
          entity:
            domain: light
    sensorpir:
      name: Sensor PIR
      description: Sensor de movimiento o grupo de sensores
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    sensorlux:
      name: Sensor LUX
      description: Sensor de luminancia o grupo de sensores
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    escena_normal:
      name: Escena Normal
      description: La Escena a activar al encender
      selector:
        target:
          entity:
            domain: scene
    escena_min:
      name: Escena Minimo
      description: La Escena a activar antes de apagar
      selector:
        target:
          entity:
            domain: scene
    ayudante_auto:
      name: Ayudante input_boolean para modo luces Auto o Manual
      description: Ayudante input_boolean que activa o desactiva el encendido y apagado automatico
      selector:
        target:
          entity:
            domain: input_boolean
    tiempo_atenuacion:
      name: Tiempo Atenuacion
      description: Tiempo para activar la escena Min en ausencia de movimiento
      default: 120
      selector:
        number:
          min: 10
          max: 300
          unit_of_measurement: seconds
    tiempo_apagado:
      name: Tiempo Apagado
      description: Tiempo para apagar las luces en ausencia de movimiento
      default: 600
      selector:
        number:
          min: 60
          max: 1500
          unit_of_measurement: seconds
    iluminacion_minima:
      name: Iluminacion Minima
      description: Iluminacion minima para el encendido automatico por PIR
      default: 60
      selector:
        number:
          min: 1
          max: 200
          unit_of_measurement: lux
    
mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input sensorpir
    to: "on"

  - platform: state
    entity_id: !input sensorpir
    to: "off"
    for: !input tiempo_atenuacion

  - platform: state
    entity_id: !input sensorpir
    to: "off"
    for: !input tiempo_apagado

variables:
  escena_normal: !input escena_normal
  escena_min: !input escena_min
  
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input grupo_luces
            state: 'off'
          - condition: state
            entity_id: !input ayudante_auto
            state: 'on'
          - condition: numeric_state
            entity_id: !input sensorlux
            below: !input iluminacion_minima
        sequence:
          - scene: !input escena_normal
      - conditions:
          - condition: state
            entity_id: !input grupo_luces
            state: 'on'
          - condition: state
            entity_id: !input ayudante_auto
            state: 'on'
          - condition: state
            entity_id: !input 'sensorpir'
            to: 'off'
            for: !input tiempo_atenuacion
        sequence:
          - scene: !input escena_min
      - conditions:
          - condition: state
            entity_id: !input grupo_luces
            state: 'on'
          - condition: state
            entity_id: !input ayudante_auto
            state: 'on'
          - condition: state
            entity_id: !input 'sensorpir'
            to: 'off'
            for: !input tiempo_apagado
        sequence:
          - service: light.turn_off
            entity_id: !input grupo_luces