blueprint:
  name: IKEA E1524/E1810 TRADFRI remote control
  description: ' 
  
  Plantilla para controlar las luces de una estancia con el mando de 5 botones de ikea.

  Que hace:

  - Boton central Activa escena Normal o apaga las luces si estan encendidas
  - Boton arriba y abajo toque simple activa las otras 2 escenas a elegir
  - Boton arriba hold activa o desactiva un ayudante input_boolean para controlar una automatizacion (la de los PIR por ejemplo)
  
  - El resto de acciones de los botones podemos configurar otras acciones
  
  Que se necesita:

  - Las escenas (3 normalmente) 
  - Un grupo con todas las luces de la estancia ( usado para apagarlas )
  - Un ayudante input_boolean que controla la automatizacion 

  '

  domain: automation
  input:
    mando:
      name: Mando Ikea
      description: Mando para la automatizacion (action)
      selector:
        entity:
          domain: sensor
    luces:
      name: Grupo de todas las luces de la estancia
      description: Las luces o grupos a controlar (para apagar)
      selector:
        entity:
          domain: light
    escena_normal:
      name: Escena Normal
      description: La Escena a activar con el boton de central
      selector:
        entity:
          domain: scene
    escena_max:
      name: Escena Maximo
      description: La Escena a activar con el boton de arriba
      selector:
        entity:
          domain: scene
    escena_min:
      name: Escena Minimo
      description: La Escena a activar con el boton de abajo
      selector:
        entity:
          domain: scene
    boolean_automatizacion:
      name: Input Boolean de la automatizacion para activar / desactivar
      description: Input Boolean de la automatizacion para activar / desactivar con el boton arriba_hold
      selector:
        entity:
          domain: input_boolean
    boton_izquierda:
      name: Toque Normal boton Izquierda (OPCIONAL)
      description: Accion para el Toque Normal boton Izquierda
      default: []
      selector:
        action: 
    boton_derecha:
      name: Toque Normal boton Derecha (OPCIONAL)
      description: Accion para el Toque Normal boton Derecha
      default: []
      selector:
        action: 
    boton_izquierda_hold:
      name: Toque Largo boton Izquierda (OPCIONAL)
      description: Accion para el Toque Largo boton Izquierda
      default: []
      selector:
        action: 
    boton_derecha_hold:
      name: Toque Largo boton Derecha (OPCIONAL)
      description: Accion para el Toque Largo boton Derecha
      default: []
      selector:
        action: 
    boton_abajo_hold:
      name: Toque Largo boton Abajo (OPCIONAL)
      description: Accion para el Toque Largo boton Abajo
      default: []
      selector:
        action: 

  source_url: https://community.home-assistant.io

mode: restart
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input 'mando'

action:
- variables:
    comando: '{{ trigger.to_state.state }}'
        
- choose:
  
  - conditions:
    - '{{ comando == ''toggle'' }}'

    sequence:
      - choose:
        - conditions:
          - condition: state
            entity_id: !input luces
            state: 'off'
          sequence:
          - service: scene.turn_on
            data: {}
            entity_id: !input escena_normal          

        default:
          - service: light.turn_off
            data: {}
            entity_id: !input luces
    
  - conditions:
    - '{{ comando == ''brightness_up_click'' }}'
    sequence:
    - service: scene.turn_on
      data: {}
      entity_id: !input escena_max

  - conditions:
    - '{{ command == ''brightness_down_click'' }}'
    sequence:
    - service: scene.turn_on
      data: {}
      entity_id: !input escena_min

  - conditions:
    - '{{ command == ''brightness_up_hold'' }}'
    sequence:
    - service: input_boolean.toggle
      data: {}
      entity_id: !input boolean_automatizacion
  
    - conditions:
    - '{{ command == ''arrow_left_click'' }}'
    sequence: !input boton_derecha

  - conditions:
    - '{{ command == ''arrow_left_hold'' }}'
    sequence: !input boton_derecha_hold

  - conditions:
    - '{{ command == ''arrow_right_click'' }}'
    sequence: !input boton_izquierda

  - conditions:
    - '{{ command == ''arrow_right_hold'' }}'
    sequence: !input boton_izquierda_hold

  - conditions:
    - '{{ command == ''brightness_down_hold'' }}'
    sequence: !input boton_abajo_hold